### ISSUE TITLE
Idea: allow release authors to make PR's against their attobot metadata branches

### ISSUE THREAD

**Issue by tkelman** [attobot/attobot#8] opened 2016-12-23 07:43 UTC
This might be a decent mechanism for revisions? It would mean metadata reviewers have to check for more variations though.

**Comment by simonbyrne** [comment] 2016-12-23 08:21
I'm not sure what you mean, can you give an example?

**Comment by tkelman** [comment] 2016-12-23 09:01
If I was the person who triggered a release PR, then attobot could potentially auto-merge pull requests filed by me against the corresponding branch of attobot/METADATA.jl as a way of making some revisions easier

**Comment by simonbyrne** [comment] 2016-12-23 09:16
It should do that already.

The main issue is if the PR has been closed (which can only be done by
people with commit access to JuliaLang/METADATA.jl), then it can't be
reopened as github sees it as a force push.

My plan is to add a webhook to METADATA itself which will autodelete
Attobot branches when the PR is closed or merged (in which case the above
will then open a new PR)

**Comment by tkelman** [comment] 2016-12-23 09:24
no one has tried yet though? https://github.com/attobot/METADATA.jl/pulls
I meant small requirements-only revisions, which aren't quite as easy to do with attobot unless you delete a tag or skip publishing some version numbers.

deleting the branch sounds like a good idea to work around that github bug.

**Comment by simonbyrne** [comment] 2016-12-23 12:03
Yes, it works, e.g.: https://github.com/JuliaLang/METADATA.jl/pull/7322

The user just has to delete the release and create a new one, and attobot will update the PR and create a new comment

**Comment by tkelman** [comment] 2016-12-23 15:46
That's not what I meant. To change the content of an existing tag you have to delete the git tag too, which is overkill if all you need to do is add a version to the requires file. I meant opening a PR against attobot's metadata fork.

**Comment by simonbyrne** [comment] 2016-12-23 21:59
Ah, I see what you mean. The problem is that these changes would only be reflected in the METADATA copy, whereas if they delete the and re-release the changes are actually reflected in the repository as well, which would probably be better in the long run.

**Comment by tkelman** [comment] 2016-12-23 23:13
both are valuable, one method of doing this requires changing things in 2 places vs the other that requires fighting with git to delete a tag or skipping version numbers for otherwise trivial modifications

**Comment by TeroFrondelius** [comment] 2017-01-02 12:00
I think this is related (or then not):
https://github.com/JuliaLang/METADATA.jl/pull/7452

https://github.com/JuliaLang/METADATA.jl/pull/7453

I tried to follow your guideline: 
https://github.com/attobot/attobot#updatingdeleting-a-release

> the easiest option is to delete the release and create a new version; AttoBot will then update the existing pull request and make a comment that it has been updated.

Attobot didn't update the pull request, it created a new pull request. Did I do something wrong? Your guideline clearly says: "create new version", which I did v0.2.1 instead of v0.2.0.

**Comment by simonbyrne** [comment] 2017-01-02 21:27
Sorry, I meant tag a new release with the same version. I'll fix the doc.

**Comment by tkelman** [comment] 2017-01-02 21:28
Is that possible without going to the command line to delete the git tag?

**Comment by simonbyrne** [comment] 2017-01-02 21:30
yes.

**Comment by tkelman** [comment] 2017-01-02 21:43
Last time I tried, github didn't delete the git tag, only the release.

**Comment by simonbyrne** [comment] 2017-01-02 21:53
Ah: it turns out you have to delete the tag separately, but this can be done via github as well. I'll update the instructions.

**Comment by TeroFrondelius** [comment] 2017-01-03 07:32
Thanks, now it worked as expected:
https://github.com/JuliaLang/METADATA.jl/pull/7453

**Comment by simonbyrne** [comment] 2019-04-16 16:49
Closed in favour of [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)

**Closed as completed by simonbyrne** 2019-04-16 16:49 UTC
