### ISSUE TITLE
REQUIRE file

### ISSUE THREAD

**Issue by andreasdominik** [attobot/attobot#51] opened 2018-09-12 16:39 UTC
Attobot complains about a missing REQUIRE file.
As I understood, the information is moved to Project.toml and manifest.toml and I assume the REQUIRE file is obsolete (because redundant).

If this is so, attobot should accept packages without REQUIRE.

Thank you for your help - attobot is great; it makes package maintenance easy as a walk in the park!
Cordially
Andreas

**Comment by simonbyrne** [comment] 2018-09-12 16:43
Yes, it should. Still need to figure out how this will work.

Duplicate of #50.

**Closed as completed by simonbyrne** 2018-09-12 16:43 UTC

**Comment by andreasdominik** [comment] 2018-09-13 06:16
thank you for caring!
